### PR TITLE
Shopping List 

### PR DESCRIPTION
**Pull request by jordantomiko**
Yesterday Simon and Olly implemented the code that enables users to add items from a recipe to a shopping list, which they can then see when they click on the Shopping List button in the Tab Bar. 

I just added 2 lines of code last night that means that the list clears automatically when you click on 'Clear' in the Shopping List view (which is the last commit)

Please review the code :) Any questions about the list functionality please ask Simon and Olly and any questions about the clear functionality feel free to ask me! :) Thanks!

### CODE REVIEW

**Review by SimonChenboYi — APPROVED** [review]
Looks Good :)

**Review by CarlyJ88 — APPROVED** [review]
Looks good, thanks team :)

**Review by ocripps24 — APPROVED** [review]
Thumbs up!

**Review by tsankhalpara — APPROVED** [review]
Looks good - I think we will be removing the clear function and changing this to add edit and delete functions

**Review by Nandini0206 — APPROVED** [review]
all looks good :)

**Pull request merged**
