### PR TITLE
More tests + Refactoring

### PR DESCRIPTION
**Pull request by SimonChenboYi**

### CODE REVIEW

**Review by jordantomiko — APPROVED** [review]
Excellent work Simon! Thank you so much for this extra work - I have gone through your code and I am learning a lot about unit testing in Swift :D Looks really good, and just to be sure I have checked out your branch and ran the tests locally - they all pass, so I definitely approve this pull request!

**Review by CarlyJ88 — COMMENTED** [review]
Great work but I'm really confused, I checked the test coverage and it now says 94% for DinnergyDB and and 100% for AppDelegate and 100% for Recipe.swift but all the view controllers are now pretty much coming up with 0%. Is this just on mine? Can we review this together because this wasn't the case before.

**Review by ocripps24 — APPROVED** [review]
This is really fantastic work. You have undertaken a considerable refactoring and the additional tests dramatically increase the test coverage of the project.

**Review by CarlyJ88 — APPROVED** [review]
Great work Simon, thanks for going through and making sure I was getting the right coverage showing on my screen

**Pull request merged**
