### PR TITLE
Map

### PR DESCRIPTION
**Pull request by ocripps24**
- Add map view
- add search by segmented control label names 
- add pins to view

### CODE REVIEW

**Review by Nandini0206 — APPROVED** [review]
Nice implementation of the map feature to find food banks and supermarkets nearby :)

**Review by jordantomiko — APPROVED** [review]
Saw this working and thanks Olly for explaining the code. Have looked through and all looks great! As a reach goal I think we should be able to input a specific location as Tara suggested but for the moment this is great progress and code looks good to me.

**Review by CarlyJ88 — APPROVED** [review]
The code looks really good. I liked your demonstration earlier and thanks for explaining the code. The comments are great just be good to make sure we remove them later :)

**Review by CarlyJ88 — COMMENTED** [review]
The code looks really good. I liked your demonstration earlier and thanks for explaining the code. The comments are great just be good to make sure we remove them later :)

**Pull request merged**
