### PR TITLE
Logo splash

### PR DESCRIPTION
**Pull request by ocripps24**
- Add logo to splash screen
- update styling of 'Add to list' button 
- update constraints to help tests pass more accurately

### CODE REVIEW

**Review by jordantomiko — DISMISSED** [review]
For some reason does not load on my launch screen  - perhaps a technical issue with my computer? I have cleaned and relaunched the build and still doesn't work.

**Review by tsankhalpara — DISMISSED** [review]
Cleaned the build before running the app - the name does not appear on the splash screen

**Review by CarlyJ88 — APPROVED** [review]
Looking good, thanks for letting me know which device to run it on :)

**Review by Nandini0206 — APPROVED** [review]
looks better :)

**Pull request merged**
